# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogovgo_site', '0015_auto_20180603_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
